name: "Terraform Apply"

on:
  push:
    branches:
      - hc-feature*

env:
  AWS_REGION: ap-southeast-2

permissions:
  id-token: write
  contents: read

jobs:
  build-and-test:
    name: Terraform Apply
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      max-parallel: 1
      matrix: { env: ["itp-prod-scp", "itp-test-scp"] }
    environment:
      name: ${{ matrix.env }}
    
    defaults:
      run:
        working-directory: "./${{ matrix.env }}"
   
    steps:
      - name: Checkout tf code in runner environment
        uses: actions/checkout@v3
      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_TEST_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GithubActionDeployment
        
      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:   
          terraform_version:  ">= 1.7.0, < 2.0.0"

      - uses: actions/cache@v3
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: ubuntu-latest-tflint-${{ hashFiles('.tflint.hcl') }}
      
              
      - name: Terraform init and validate
        run: |
              echo "** Running Terraform Init **"
              terraform init
              echo "** Running Terraform Validate **"
              terraform validate
              echo "**Terraform format**"
              terraform fmt  

      - name: Run Terraform apply
        run: |
              echo "** Running Terraform Apply **"
              terraform apply

  
    


