name: "Terraform Plan"

on:
  push:
    branches:
      - hc-feature

env:
  AWS_REGION: ap-southeast-2

permissions:
  id-token: write
  contents: read

jobs:
  build-and-test:
    name: Terraform Plan
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        environment: ['itp-prod-scp','itp-test-scp']
      fail-fast: true
      max-parallel: 1
    steps:
      - name: Checkout tf code in runner environment
        uses: actions/checkout@v3
      - name: Configure AWS Credentials Action For GitHub Actions
        uses:  aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_TEST_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GithubActionDeployment
        
      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:
              terraform_version: 1.1.7
       
      
      - name: Terraform init and validate
        run: |
            echo "** Running Terraform Init **"
            terraform init
            
            echo "** Running Terraform Validate **"
            terraform validate

            echo "**Terraform format**"
            terraform fmt  
         
      - name: Run Terraform plan
        run: |
            echo "** Running Terraform Plan **"
            terraform plan