name: "Terraform Plan"

on:
  push:
    branches:
      - hc-feature

env:
  AWS_REGION: ap-southeast-2

permissions:
  id-token: write
  contents: read

jobs:
  build-and-test:
    name: CI Pipeline
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix: { env: ["itp-prod-scp", "itp-test-scp"] }
    environment: ${{ matrix.env }}
    defaults:
      run:
        working-directory: "./${{ matrix.env }}"
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          role-to-assume: ${{ secrets.AWS_TEST_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GithubActionDeployment
          
      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Verify that the configuration files are syntactically valid
        run: terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan -no-color
